# Generated by Django 5.2.12 on 2026-03-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patients_phn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='insurance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
