# Generated by Django 5.2.12 on 2026-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patients_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='nom_parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='tel_parent',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
