# Generated by Django 5.2.12 on 2026-03-25 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_patients_insurance_alter_patients_nom_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
