# Generated by Django 5.2.12 on 2026-03-25 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_patients_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traceaction',
            old_name='date_action',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='reste_token',
            name='email',
        ),
        migrations.RemoveField(
            model_name='traceaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='traceaction',
            name='table_concernee',
        ),
        migrations.RemoveField(
            model_name='traceaction',
            name='type_action',
        ),
        migrations.AddField(
            model_name='reste_token',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceaction',
            name='action',
            field=models.CharField(default='Initial action', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reste_token',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='traceaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patients')),
            ],
        ),
    ]
