# Generated by Django 6.0.4 on 2026-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_patients_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='horaires_travail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/photos/'),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
    ]
