# Generated by Django 5.2.12 on 2026-03-29 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date_rdv'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date_consultation'], 'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'verbose_name': 'Diagnostic', 'verbose_name_plural': 'Diagnostics'},
        ),
        migrations.AlterModelOptions(
            name='traitement',
            options={'verbose_name': 'Traitement', 'verbose_name_plural': 'Traitements'},
        ),
        migrations.RenameField(
            model_name='diagnostic',
            old_name='commentaire',
            new_name='commentaire_medical',
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='explication_parent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultations.appointment'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='poids',
            field=models.DecimalField(decimal_places=2, help_text='en kg', max_digits=5),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='taille',
            field=models.DecimalField(decimal_places=2, help_text='en cm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=37.0, help_text='en °C', max_digits=4),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='gravite',
            field=models.CharField(choices=[('LEGERE', 'Légère'), ('MODEREE', 'Modérée'), ('SEVERE', 'Sévère')], default='LEGERE', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='type_maladie',
            field=models.CharField(choices=[('AIGU', 'Aigu'), ('CHRONIQUE', 'Chronique'), ('ALLERGIQUE', 'Allergique'), ('INFECTIEUX', 'Infectieux'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='duree',
            field=models.CharField(help_text='ex: 7 jours, 2 semaines', max_length=100),
        ),
    ]
