# Generated by Django 6.0.4 on 2026-04-18 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_appointment_options_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result_value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'Élevé'), ('LOW', 'Bas')], default='NORMAL', max_length=10)),
                ('test_date', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Résultat de laboratoire',
                'verbose_name_plural': 'Résultats de laboratoire',
            },
        ),
    ]
