# Generated by Django 6.0.4 on 2026-04-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_labresult'),
        ('users', '0011_doctors_actif_doctors_horaires_travail_doctors_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='users.doctors'),
        ),
        migrations.AddField(
            model_name='traitement',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='users.patients'),
        ),
    ]
