# Generated by Django 6.0.4 on 2026-04-18 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0004_labresult'),
        ('users', '0011_doctors_actif_doctors_horaires_travail_doctors_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_doc', models.CharField(choices=[('ORDONNANCE', 'Ordonnance'), ('RADIO', 'Radiographie'), ('ANALYSE', 'Analyse de laboratoire'), ('COMPTE_RENDU', 'Compte rendu'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='consultations.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.patients')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_upload'],
            },
        ),
    ]
