# Generated by Django 5.2.12 on 2026-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_doctors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
