# Generated by Django 5.2.12 on 2026-03-29 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_address_options_alter_doctors_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='parent',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'PARENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
