# Generated by Django 5.2.12 on 2026-04-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_alter_patients_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'allergène", max_length=150)),
                ('reaction', models.CharField(choices=[('LEGERE', 'Légère'), ('MODEREE', 'Modérée'), ('SEVERE', 'Sévère'), ('CRITIQUE', 'Critique')], default='LEGERE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('date_detection', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='users.patients')),
            ],
            options={
                'verbose_name': 'Allergie',
                'verbose_name_plural': 'Allergies',
                'ordering': ['-date_detection'],
            },
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type_antecedent', models.CharField(choices=[('MEDICAL', 'Médical'), ('CHIRURGICAL', 'Chirurgical'), ('FAMILIAL', 'Familial'), ('AUTRE', 'Autre')], default='MEDICAL', max_length=20)),
                ('date_declaration', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='users.patients')),
            ],
            options={
                'verbose_name': 'Antécédent',
                'verbose_name_plural': 'Antécédents',
                'ordering': ['-date_declaration'],
            },
        ),
    ]
